/*
 * AddServiceDialog.java
 *
 * Created on June 27, 2006, 2:30 PM
 */

package sdtconnector;
import com.opengear.util.IconLoader;
import org.jdesktop.swingx.decorator.Highlighter;
import org.jdesktop.swingx.decorator.HighlighterPipeline;


public class AddServiceDialog extends javax.swing.JDialog {

    /** Creates new form AddServiceDialog */
    public AddServiceDialog(java.awt.Frame parent, boolean modal, Service service) {
        super(parent, modal);
        initComponents();
        this.service = service;

        closeButton.setIcon(IconLoader.getButtonIcon("ok"));
        addLauncherButton.setIcon(IconLoader.getButtonIcon("add"));
        editLauncherButton.setIcon(IconLoader.getButtonIcon("edit"));
        removeLauncherButton.setIcon(IconLoader.getButtonIcon("remove"));
        nameField.setText(service.getName());
        launcherJList.setModel(new ca.odell.glazedlists.swing.EventListModel(service.getLauncherList()));
        launcherJList.setRolloverEnabled(true);
        launcherJList.setHighlighters(new HighlighterPipeline(new Highlighter[] {
            Highlighter.notePadBackground
        }));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        launcherJList = new org.jdesktop.swingx.JXList();
        addLauncherButton = new javax.swing.JButton();
        editLauncherButton = new javax.swing.JButton();
        removeLauncherButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonAction(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Local -> Remote Port Redirections"));
        launcherJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                launcherJListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(launcherJList);

        addLauncherButton.setText("Add");
        addLauncherButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        addLauncherButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addLauncherButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        addLauncherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLauncherButtonaddClientActionPerformed(evt);
            }
        });

        editLauncherButton.setText("Edit");
        editLauncherButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        editLauncherButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editLauncherButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        editLauncherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLauncherButtoneditClientActionPerformed(evt);
            }
        });

        removeLauncherButton.setText("Remove");
        removeLauncherButton.setEnabled(false);
        removeLauncherButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        removeLauncherButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        removeLauncherButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        removeLauncherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLauncherButtonremoveClientActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(addLauncherButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(editLauncherButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, removeLauncherButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(addLauncherButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(editLauncherButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(removeLauncherButton)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setText("Service Name");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, closeButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void launcherJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_launcherJListValueChanged
        editLauncherButton.setEnabled(launcherJList.isSelectionEmpty() == false);
        removeLauncherButton.setEnabled(launcherJList.isSelectionEmpty() == false &&
                ((Launcher) launcherJList.getSelectedValue()).getRecordID() > SDTManager.initialRecordID());
    }//GEN-LAST:event_launcherJListValueChanged

    private void closeButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonAction
        setVisible(false);
        dispose();
        service.setName(nameField.getText());
    }//GEN-LAST:event_closeButtonAction

    private void removeLauncherButtonremoveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLauncherButtonremoveClientActionPerformed
        if (launcherJList.isSelectionEmpty()) {
            return;
        }
        service.removeLauncher((Launcher) launcherJList.getSelectedValue());
        SDTManager.updateService(service);
    }//GEN-LAST:event_removeLauncherButtonremoveClientActionPerformed

    private void editLauncherButtoneditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLauncherButtoneditClientActionPerformed
        if (launcherJList.isSelectionEmpty()) {
            return;
        }
        Launcher launcher = (Launcher) launcherJList.getSelectedValue();
        AddLauncherDialog dlg = new AddLauncherDialog((java.awt.Frame) this.getParent(), true, launcher);
        
        dlg.setTitle("Edit Port Redirection");
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        if (dlg.getReturnStatus() == dlg.RET_OK) {
            SDTManager.updateService(service);
        }
    }//GEN-LAST:event_editLauncherButtoneditClientActionPerformed

    private void addLauncherButtonaddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLauncherButtonaddClientActionPerformed
        Launcher launcher = new Launcher();
        AddLauncherDialog dlg = new AddLauncherDialog((java.awt.Frame) this.getParent(), true, launcher);
        
        dlg.setTitle("Add Port Redirection");
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        if (dlg.getReturnStatus() == dlg.RET_OK) {
            service.addLauncher(launcher);
            SDTManager.updateService(service);
        }
    }//GEN-LAST:event_addLauncherButtonaddClientActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLauncherButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton editLauncherButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXList launcherJList;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton removeLauncherButton;
    // End of variables declaration//GEN-END:variables

    private Service service;
}
