#!/bin/bash

function tarup () {	
	distfile="$1"
	shift

	cd /tmp
	rm -rf "$TARDIR" &> /dev/null
	mkdir "$TARDIR"
	for file in $*; do
		cp "$file" "$TARDIR"
	done
	tar -cz "$TARDIR" > "$distfile"
	rm -rf "$TARDIR"
	cd - &> /dev/null
	mv "/tmp/$distfile" "$DISTDIR"
}

OLDDIR="$PWD"
cd "`dirname $0`/.."

ROOTDIR="$PWD"
DISTDIR="$ROOTDIR/dist"
TOOLSDIR="$ROOTDIR/tools"
CONFIGDIR="$ROOTDIR/config"

if [[ ! -d  "$DISTDIR" ]] ; then
	echo "Can't find dist directory: $DISTDIR"
	exit 1
fi
if [[ ! -d  "$TOOLSDIR" ]] ; then
	echo "Can't find tools directory: $TOOLSDIR"
	exit 1
fi
if [[ ! -d  "$CONFIGDIR" ]] ; then
	echo "Can't find config directory: $CONFIGDIR"
	exit 1
fi
if [[ ! -e "$DISTDIR/sdtcon.jar" ]] || [[ ! -e "$DISTDIR/sdtcon-mac.jar" ]] ; then
	echo "Can't find sdtcon JAR files in $DISTDIR, have you built them?"
	exit 1
fi

VERSION=`grep VERSION $ROOTDIR/src/sdtconnector/SDTConnector.java|sed 's/.*\"\(.*\)\".*/\1/'`
echo "SDTConnector version: $VERSION"

TARDIR="sdtconnector-$VERSION"

tarup "sdtconnector-$VERSION.tar.gz" "$TOOLSDIR/SDTConnector" "$DISTDIR/sdtcon.jar"
APPNAME="Opengear SDTConnector" SHORTNAME="SDTConnector" VENDOR="Opengear" makensis "$TOOLSDIR/SDTConnector.nsi"
mv "$DISTDIR/SDTConnectorSetup.exe" "$DISTDIR/SDTConnectorSetup-$VERSION.exe"

echo "***"
echo "*** Mac OS X distribution must be created manually - use Xcode Jar Bundler"
echo "*** with dist/sdtcon-mac.jar and images/SDTConnector.icns"
echo "***"

cd "$OLDDIR" &> /dev/null
