#!/bin/bash

function tarup () {	
	distfile="$1"
	configfile="$2"
	shift; shift

	cd /tmp
	rm -rf "$TARDIR" &> /dev/null
	mkdir "$TARDIR"
	cp "$configfile" "$TARDIR/defaults.xml"
	for file in $*; do
		cp "$file" "$TARDIR"
	done
	tar -cz "$TARDIR" > "$distfile"
	rm -rf "$TARDIR"
	cd - &> /dev/null
	mv "/tmp/$distfile" "$DISTDIR"
}

OLDDIR="$PWD"
cd "`dirname $0`/.."

ROOTDIR="$PWD"
DISTDIR="$ROOTDIR/dist"
TOOLSDIR="$ROOTDIR/tools"

if [[ ! -d  "$DISTDIR" ]] ; then
	echo "Can't find dist directory: $DISTDIR"
	exit 1
fi
if [[ ! -d  "$TOOLSDIR" ]] ; then
	echo "Can't find tools directory: $TOOLSDIR"
	exit 1
fi
if [[ ! -e "$DISTDIR/sdtcon.jar" ]] || [[ ! -e "$DISTDIR/sdtcon-mac.jar" ]] ; then
	echo "Can't find sdtcon JAR files in $DISTDIR, have you built them?"
	exit 1
fi

VERSION=`grep VERSION $ROOTDIR/src/sdtconnector/SDTConnector.java|sed 's/.*\"\(.*\)\".*/\1/'`
echo "SDTConnector version: $VERSION"

TARDIR="sdtconnector-$VERSION"

tarup "sdtconnector-$VERSION.tar.gz" "$TOOLSDIR/defaults.xml" "$TOOLSDIR/SDTConnector" "$DISTDIR/sdtcon.jar"
tarup "sdtconnector-mac-$VERSION.tar.gz" "$TOOLSDIR/defaults.xml" "$TOOLSDIR/SDTConnector" "$DISTDIR/sdtcon-mac.jar"

if [[ -e "$TOOLSDIR/defaults-prop.xml" ]] ; then
	tarup "sdtconnector-$VERSION-prop.tar.gz" "$TOOLSDIR/defaults-prop.xml" "$TOOLSDIR/SDTConnector" "$DISTDIR/sdtcon.jar"
	tarup "sdtconnector-mac-$VERSION-prop.tar.gz" "$TOOLSDIR/defaults-prop.xml" "$TOOLSDIR/SDTConnector" "$DISTDIR/sdtcon-mac.jar"
fi

cd "$OLDDIR" &> /dev/null
